resources:
  - repo: self

trigger: none

pr:
  branches:
    include:
      - master
  paths:
    exclude:
      - .azure/*
      - .github/*
      - .vscode/*
      - functions/*
      - tools/*
      - LICENSE
      - README.md
      - /**/README.md
      - .*

jobs:
  ##
  # Testing pipeline suitable for PRs validation only.
  # It does the following:
  # - lints source code, styles, and html templates;
  # - executes unit tests;
  # - executes e2e tests.
  # Note on environment variables:
  # - all envitonment variables (if any, not required here) should be defined in Azure DevOps UI.
  ##
  - job: Testing_pipeline
    timeoutInMinutes: 60
    cancelTimeoutInMinutes: 10

    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: NodeTool@0
        displayName: 'Use specific node version'
        inputs:
          versionSpec: '12.16.1'

      - script: |
          npm i -g npm@6.14.4
          npm i -g typescript
          npm i -g @angular/cli
          npm i -g @nrwl/schematics
          npm i -g yarn
          yarn install --frozen-lockfile
          bash tools/shell/lint.sh affected
          if [ $? -ne 0 ]; then
            exit 1
          fi
          bash tools/shell/test.sh single-run affected
          if [ $? -ne 0 ]; then
            exit 1
          fi
          echo 524288 | sudo tee /proc/sys/fs/inotify/max_user_watches
          bash tools/shell/e2e.sh affected

      - task: ArchiveFiles@2
        displayName: 'Archive files'
        inputs:
          rootFolderOrFile: '$(System.DefaultWorkingDirectory)'
          includeRootFolder: false

      - task: PublishBuildArtifacts@1
        displayName: 'Publish artifacts: drop'
